name: Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable:
    uses: ./.github/Workflows/reusable.yml
    with:
      username: ${{ github.actor }}
    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}
